import org.gradle.internal.os.OperatingSystem

plugins {
    id 'java-library'
}

repositories {
    mavenCentral()
}

ext.lwjglVersion = "3.4.1"

switch (OperatingSystem.current()) {
    case OperatingSystem.LINUX:
        ext.lwjglNatives = "natives-linux"
        def osArch = System.getProperty("os.arch")
        if (osArch.startsWith("arm") || osArch.startsWith("aarch64")) {
            ext.lwjglNatives += osArch.contains("64") || osArch.startsWith("armv8") ? "-arm64" : "-arm32"
        } else if (osArch.startsWith("ppc")) {
            ext.lwjglNatives += "-ppc64le"
        } else if (osArch.startsWith("riscv")) {
            ext.lwjglNatives += "-riscv64"
        }
        break
    case OperatingSystem.WINDOWS:
        ext.lwjglNatives = "natives-windows"
        break
}

dependencies {
    api project(":core")

    api platform("org.lwjgl:lwjgl-bom:$lwjglVersion")
    api "org.lwjgl:lwjgl"
    api "org.lwjgl:lwjgl-freetype"

    implementation "org.lwjgl:lwjgl::$lwjglNatives"
    implementation "org.lwjgl:lwjgl-freetype::$lwjglNatives"
}

base {
    archivesName = "jmsdfgen-ext"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = "jmsdfgen-ext"
        }
    }
}
